### ISSUE TITLE
`is.eq ct.status (f: f.dnat)` doesn't work

### ISSUE THREAD

**Issue by MagicRB** [chayleaf/notnft#1]
`is.eq ct.status (f: f.dnat)` compiles down to `ct status == dnat` but that isn't the correct form, it is accepted by nftables, but it doesn't actually work. The correct form is `ct status dnat` without the `==`.

**Comment by MagicRB** [comment]
Turns out the correct operator to use is `in` for some bizarre reason. so `is."in" ct.status (f: f.dnat)` works like a charm.

**Comment by chayleaf** [comment]
`is ct.status (f: f.dnat)` might work as well

**Comment by MagicRB** [comment]
Will try and report back tomorrow, thanks for the library, works amazingly
