### ISSUE TITLE
Maps and multiple source types

### ISSUE THREAD

**Issue by MagicRB** [chayleaf/notnft#2]
According to some source, namely [this one](https://unix.stackexchange.com/questions/671805/nftables-map-port-to-ipport-for-dnat), it should be possible to have a map such as `ipv4_addr . inet_service : ipv4_addr . inet_service`, however notnft currently denies this [here](https://github.com/chayleaf/notnft/blob/master/default.nix#L587). I'm not sure if this is even valid syntax, as always the sources are scarce and confused, but I think it should work.

**Comment by MagicRB** [comment]
https://git.netfilter.org/nftables/tree/tests/py/ip/dnat.t.json#n384 that test case confirms that it should be allowed, though I'm not even sure how to get this working in the simple case of a singular key.

**Comment by MagicRB** [comment]
okay so what I have that currently does ~not~ work is:
```nix
          wan_dnat =
            add notnft.dsl.map {
              map = f: f.inet_service; #  f.ipv4_addr]
              type = f: [f.ipv4_addr f.inet_service];
              flags = f: with f; [interval];
            } [
              [["192.168.1.1" 6666] 6666] # ["10.0.0.1" 6666]
            ];
```
and
```nix
            [
              (dnat {
                addr.map = {
                  key = concat [payload.ip.daddr payload.tcp.dport];
                  data = "@wan_dnat";
                };
              })
            ]
```

appears I had a mistake somewhere else, still don't know how to map many to many...

**Comment by MagicRB** [comment]
I made an attempt with the following patch:
```diff
diff --git a/default.nix b/default.nix
index be8f143..555bae6 100644
--- a/default.nix
+++ b/default.nix
@@ -557,7 +557,7 @@ let
           let expr = ret.elem; in assert lib.assertMsg
             (if builtins.isList expr then builtins.all (elem:
               if builtins.isList elem && builtins.length elem == 2
-              then isValidExpr CTX_F_RHS (builtins.head elem) && isValidExpr CTX_F_SET_RHS (builtins.head (builtins.tail elem))
+              then isValidExpr CTX_F_SET_RHS (builtins.head elem) && isValidExpr CTX_F_SET_RHS (builtins.head (builtins.tail elem))
               else isValidExpr CTX_F_RHS elem) expr
             else isImmediateExpr expr)
             "Set/map add command's exprs are invalid in this context";
@@ -584,12 +584,12 @@ let
       } else {})
       // (if withExtraFields && isMap != false then builtins.mapAttrs mkOpt {
         map = {
-          type = types.type;
+          type = lib.types.either (lib.types.nonEmptyListOf types.type) types.type;
           description =
             if isMap == true then
-              "Type of values this map maps to."
+              "Type(s) of values this map maps to."
             else
-              "Type of values this set maps to (i.e. this set is a map).";
+              "Type(s) of values this set maps to (i.e. this set is a map).";
         };
       } else {}) // (if withExtraFields then builtins.mapAttrs mkOpt {
         policy = {
```

but `then isValidExpr CTX_F_SET_RHS (builtins.head elem) && isValidExpr CTX_F_SET_RHS (builtins.head (builtins.tail elem))` is not quite working as expected, truth be told I've no clue how the `CTX` thing works.

**Comment by chayleaf** [comment]
the code you sent doesnt seem to have any errors and compiles to `{"nftables":[{"add":{"table":{"family":"inet","name":"global"}}},{"add":{"chain":{"family":"inet","name":"test","table":"global"}}},{"add":{"map":{"elem":[[["192.168.1.1",6666],6666]],"family":"inet","flags":["interval"],"map":"inet_service","name":"wan_dnat","table":"global","type":["ipv4_addr","inet_service"]}}},{"add":{"rule":{"chain":"test","expr":[{"dnat":{"addr":{"map":{"data":"@wan_dnat","key":{"concat":[{"payload":{"field":"daddr","protocol":"ip"}},{"payload":{"field":"dport","protocol":"tcp"}}]}}}}}],"family":"inet","table":"global"}}}]}`, is there a non-working example?

**Comment by MagicRB** [comment]
@chayleaf here:
```nix
add notnft.dsl.map {
  map = f: [f.ipv4_addr f.inet_service];
  type = f: [f.ipv4_addr f.inet_service];
  flags = f: with f; [interval];
} [
  [["10.0.0.2" 22] ["192.168.1.1" 22]]
];
```

more ref: https://github.com/google/nftables/issues/185

**Comment by MagicRB** [comment]
good news:
```nix
add notnft.dsl.map {
  map = f: [f.ipv4_addr f.inet_service];
  type = f: [f.ipv4_addr f.inet_service];
  flags = f: with f; [interval];
} [
  [(concat ["10.0.0.2" 22]) (concat ["192.168.1.1" 22])]
];
```
results in:
```nft
map slan_dnat {
  type ipv4_addr . inet_service : ipv4_addr . inet_service
  flags interval
  elements = { 10.0.0.2 . 22 : 192.168.1.1 . 22 }
}
```

but this still requires:
```nix
diff --git a/default.nix b/default.nix
index be8f143..a9d0f56 100644
--- a/default.nix
+++ b/default.nix
@@ -584,12 +584,12 @@ let
       } else {})
       // (if withExtraFields && isMap != false then builtins.mapAttrs mkOpt {
         map = {
-          type = types.type;
+          type = lib.types.either (lib.types.nonEmptyListOf types.type) types.type;
           description =
             if isMap == true then
-              "Type of values this map maps to."
+              "Type(s) of values this map maps to."
             else
-              "Type of values this set maps to (i.e. this set is a map).";
+              "Type(s) of values this set maps to (i.e. this set is a map).";
         };
       } else {}) // (if withExtraFields then builtins.mapAttrs mkOpt {
         policy = {
```

which for my usecase is good enough, tho I wonder if we could get rid of those `concat`s somehow.

Edit:
omitting the `concat` on the left leads to a runtime error, omitting it on the right leads to a eval error.

**Comment by chayleaf** [comment]
applied it in https://github.com/chayleaf/notnft/commit/7d72e0b5c268921da51388fe1e4180637c3ae97d
